GET http://localhost:8000/clientes

###

GET http://localhost:8000/clientes/1

###

POST http://localhost:8000/clientes
Content-Type: application/json

{
    "nome": "Raphael",
    "email": "raphael@email.com",
    "telefone": "11999999999"
}

###

PUT http://localhost:8000/clientes/1
Content-Type: application/json

{
    "nome": "Raphael Marinho",
    "email": "raphael@email.com",
    "telefone": "11999999999"
}

###

DELETE http://localhost:8000/clientes/1
